<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>

<div class="products wrapper grid products-grid">
    <ol class="products list items product-items">
        <?php echo $block->getChildHtml('tech_list') ?>
    </ol>
</div>

<div class="loading-pro"><img src="<?php echo $block->getViewFileUrl('images/load.gif'); ?>" border="0"></div>
