<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_tech = $this->helper('Tech\Catalog\Helper\Output');

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>

    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>

    <?php $iterator = 1; ?>

    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
    <?php foreach ($_productCollection as $_product): ?>
        <?php /* @escapeNotVerified */
        echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>

        <div class="product-item-info" data-container="product-grid">
            <?php
            $productImage = $block->getImage($_product, $image);
            if ($pos != null) {
                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                    . 'top:' . $productImage->getHeight() . 'px;"';
            }
            ?>
            <?php // Product Image ?>
            <a href="<?php /* @escapeNotVerified */
            echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                <?php if($_tech->isProductNew($_product)): ?>
                    <style>
                        .new-product span {
                            position: absolute;
                            left: 20px;
                            top: 26px;
                            z-index: 1;
                            color: black;
                            font-size: 18px;

                        }

                        .new-product {
                            position: relative;
                            z-index: 2;
                            text-align: left;
                        }

                        .new-product:after{
                            border-top: 110px solid rgba(252,215,211,0.8);
                            content: '';
                            position: absolute;
                            width: 0;
                            height: 0;
                            border-right: 130px solid transparent;
                            top: 0px;
                            left: 0px;
                        }

                    </style>

                    <div class="new-product"><span><?php echo __('New') ?></span></div>
                <?php endif; ?>



                <?php if($_helper->productAttribute($_product, $_product->getSalePrice(), 'sale_price')): ?>
                    <style>
                        .product-special-price span {
                            position: absolute;
                            right: 15px;
                            top: 6px;
                            z-index: 1;
                            color: black;
                            font-size: 18px;
                            width: 47px;
                            text-align: right;

                        }

                        .product-special-price {
                            position: relative;
                            z-index: 2;
                            text-align: left;
                        }

                        .product-special-price:after{
                            border-top: 110px solid rgba(252,215,211,0.8);
                            content: '';
                            position: absolute;
                            width: 0;
                            height: 0;
                            border-left: 130px solid transparent;
                            top: 0;
                            right: 0;
                        }

                    </style>

                    <div class="product-special-price"><span><?php echo __('Special Price') ?></span></div>
                <?php endif; ?>







                <?php echo $productImage->toHtml(); ?>

                <?php if(!$_tech->getStockItem((string)$_product->getId())->getIsInStock()): ?>
                    <style>
                        .product-in-stock span {
                            position: absolute;
                            right: 15px;
                            top: -66px;
                            z-index: 1;
                            color: black;
                            font-size: 18px;
                            width: 47px;
                            text-align: right;

                        }

                        .product-in-stock {
                            position: relative;
                            z-index: 2;
                            text-align: left;
                        }

                        .product-in-stock:after{
                            border-bottom: 110px solid rgba(252,215,211,0.8);
                            content: '';
                            position: absolute;
                            width: 0;
                            height: 0;
                            border-left: 130px solid transparent;
                            bottom: 4px;
                            right: 0px;
                        }

                    </style>

                    <div class="product-in-stock"><span><?php echo __('In stock') ?></span></div>
                <?php endif; ?>
            </a>

            <?php

            $name = $_helper->productAttribute($_product, $_product->getName(), 'name');
            $out = mb_strlen($name) > 15 ? mb_substr($name,0,15)."..." : $name;

            ?>

            <div class="product details product-item-details">
                <?php
                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                ?>
                <strong class="product name product-item-name">
                    <a class="product-item-link"
                       href="<?php /* @escapeNotVerified */
                       echo $_product->getProductUrl() ?>">
                        <?php /* @escapeNotVerified */
                        echo $out ?>
                    </a>
                </strong>
                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                <?php /* @escapeNotVerified */
                echo $block->getProductPrice($_product) ?>
                <style>
                    .price-container .price:before{
                        content: '<?php echo __('Price').': ' ?>';
                    }
                </style>
                <div data-role="add-to-links"
                     class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                    <?php // if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                    <a href="#"
                       class="action towishlist"
                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                       data-post='<?php /* @escapeNotVerified */
                       echo $block->getAddToWishlistParams($_product); ?>'
                       data-action="add-to-wishlist"
                       role="button">
                    </a>
                    <?php // endif; ?>

                </div>

                <?php echo $block->getProductDetailsHtml($_product); ?>


            </div>
        </div>
        <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
    <?php endforeach; ?>
<?php endif; ?>
