<?php $collection = $this->getCollection(); ?>

<div class="slider-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <div data-role="loader" class="loading-mask">
        <div class="loader">
            <img src="http://expose.tech.com/pub/static/frontend/Tech/expose/he_IL/images/loader-1.gif"
                 alt="Loading...">
        </div>
    </div>
</div>


<script type="text/x-magento-init">
{
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "data": [
                <?php $i = 0; ?>
                <?php foreach ($collection as $post): ?>
        <?php echo ($i != 0) ? ',' : '' ?>
                    {"img":"<?php echo $this->getBaseUrl() . 'pub/media' . $post->getImg(); ?>",
                    "caption":"<?php echo $post->getLink() ?>","position":"<?php echo $post->getPosition() ?>",
                    "isMain":<?php echo ($i++ != 0) ? 'false' : 'true' ?>}
                <?php endforeach ?>
                ],

                "options": {
                    "autoplay": true,
                    "loop": true,
                    "keyboard": true,
                    "arrows": true,
                    "allowfullscreen": false,
                    "showCaption": false,
                    "width": "100%",
                    "transitionduration": 500,
                    "transition": "slide",
                    "navarrows": true,
                    "navtype": "slides"
                },
                "fullscreen": {
                    "nav": "thumbs",
                    "loop": true,
                    "navdir": "vertical",
                    "arrows": false,
                    "showCaption": false,
                    "transitionduration": 500,
                    "transition": "dissolve"
                },
                "breakpoints": {"mobile":{"conditions":{"max-width":"767px"},"options":{"options":{"nav":"dots"}}}}            }
        }
    }

</script>

<script>
    require([
        "jquery"
    ], function ($) {
        $(document).ready(function () {
            setTimeout(function () {
                $(".fotorama__stage__frame").mouseup(function () {
                    if ($('img', this).attr('alt') != '') window.open($('img', this).attr('alt'), "_blank");
                });
            }, 1000)
        });
    });
</script>
