
<div class="page-title-wrapper product">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper" itemprop="name"
              style="background-color:<?php echo $this->getCategoryColor() ?>">
            <?php echo $this->getTitle() ?>
        </span>
    </h1>

    <h2 class="product-name">
        <span class="base" data-ui-id="page-title-wrapper" itemprop="name">
            <?php echo $this->getProductName() ?>
        </span>
    </h2>
</div>
