<?php $collection = $this->getCollection(); ?>

<div class="metro">

    <ul>
        <?php foreach ($collection as $post): ?>
            <li><a href="#"><img class="metro-img"
                                 src="<?php echo $this->getBaseUrl() . 'pub/media' . $post->getImage(); ?>"/>

                    <div>
                        <p style="height: 40%;width: 100%"></p>
                        <label><?php echo $post->getName() ?></label>
                    </div>


                </a>


            </li>
        <?php endforeach ?>
    </ul>

</div>