<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>


<?php if ($_productCollection->count()): ?>
<?php $image = 'special_product_grid'; ?>

<h1 class="special-title"><span>פרטים נבחרים באתר</span></h1>

<div class="swiper-container">
    <div class="swiper-wrapper">
        <?php foreach ($_productCollection as $_product): ?>

            <div class="swiper-slide item product product-item">
                <?php
                $productImage = $block->getImage($_product, $image);
                ?>
                <?php
                $color = $_product->getCatColor();

                $rgb = 'rgba(' . hexdec(substr($color, 1, 2)) . ',' . hexdec(substr($color, 3, 2)) . ',' . hexdec(substr($color, 5, 2)) . ', 0.8)';
                ?>
                <style>
                    <?php echo '#pro-'.$_product->getId().':after'; ?>
                    {
                        border-top-color:<?php echo $rgb; ?>;
                        border-bottom-color:<?php echo $rgb; ?>;
                    }
                    <?php echo '#pro-'.$_product->getId().' span'; ?>
                    {
                        border-bottom: 2px solid <?php echo $rgb; ?>;
                    }
                </style>
                <div class="product-item-info" data-container="product-grid">
                    <a id="<?php echo 'pro-' . $_product->getId(); ?>" href="<?php /* @escapeNotVerified */
                    echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>

                    <?php

                    $name = $_helper->productAttribute($_product, $_product->getName(), 'name');
                    $out = mb_strlen($name) > 20 ? mb_substr($name, 0, 22) . "..." : $name;

                    ?>

                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */
                               echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */
                                echo $out; ?>
                            </a>
                        </strong>

                        <?php /* @escapeNotVerified */
                        echo $block->getProductPrice($_product) ?>

                        <style>
                            .price-container .price:before{
                                content: '<?php echo __('Price').': ' ?>';
                            }
                        </style>

                        <div class="product-item-inner">
                            <div
                                class="product actions">

                                <div data-role="add-to-links"
                                     class="actions-secondary">
                                    <a href="#" style="color: <?php echo $rgb; ?>;border-right: 1px solid <?php echo $rgb; ?>;"
                                       class="action towishlist"
                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       data-post='<?php /* @escapeNotVerified */
                                       echo $block->getAddToWishlistParams($_product); ?>'
                                       data-action="add-to-wishlist"
                                       role="button">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
</div>

<script>
    require(['jquery', 'swiper'], function ($) {
        var swiper = new Swiper('.swiper-container', {
            pagination: '.swiper-pagination',
            nextButton: '.swiper-button-next',
            prevButton: '.swiper-button-prev',
            slidesPerView: 4,
            centeredSlides: false,
            paginationClickable: true,
            spaceBetween: 20
        });
    });
</script>

<?php endif; ?>