
<?php if ($block->canShowBlock()): ?>
    <div class="block filter">
        <div class="block-title filter-title">
            <strong><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
        </div>

        <div class="block-content filter-content">

            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if (!$wrapOptions): ?>
                    <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Shopping Options') ?></strong>
                    <dl class="filter-options" id="narrow-by-list">
                <?php $wrapOptions = true; endif; ?>
                    <?php if ($filter->getItemsCount()): ?>
                        <dt role="heading" aria-level="3" class="filter-options-title"><?php echo $block->escapeHtml(__($filter->getName())) ?></dt>
                        <dd class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></dd>
                    <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </dl>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

<script>
    require([
        "jquery"
    ], function($){

        var page = 2; var s=1; var end = 0;
        var cats = [];var colors= [];var sizes = [];

        $(".more").click(function(){
            $(this).next().toggleClass("no-display");
            if($(this).next().hasClass("no-display"))
                $(this).text('<?php echo __('View More') ?>');
            else
                $(this).text('<?php echo __('Close') ?>');
        });

        $(".chk_filtered_cat, .swatch-option.color, .chk_filtered_size").click(function(){
            $.each($('.chk_filtered_cat'), function() {
                var index = cats.indexOf(this.value);
                if($(this).is(':checked')) {
                    if(index==-1) cats.push(this.value);
                }else{
                    if(index!=-1) cats.splice(index, 1);
                }
            });

            if(this.getAttribute('option-type')==1){
                $(this).toggleClass('selected');
                var index = colors.indexOf(this.getAttribute('option-id'));
                if($(this).hasClass('selected')){
                    if(index==-1) colors.push(this.getAttribute('option-id'));
                }else{
                    if(index!=-1) colors.splice(index, 1);
                }
            }

            $.each($('.chk_filtered_size'), function() {
                var index = sizes.indexOf(this.value);
                if($(this).is(':checked')) {
                    if(index==-1) sizes.push(this.value);
                }else{
                    if(index!=-1) sizes.splice(index, 1);
                }
            });
            $('.loading-pro').show();
            $.ajax({
                url: '/filtered/category?cat='+cats.join()+'&color='+colors.join()+'&size='+sizes.join(),
                dataType: 'html',
                success: function (res) {
                    $('.products.list.items.product-items').html(res);
                    $('.loading-pro').hide();
                    page = 2;  s=1;  end = 0;
                }
            });
        });

        $(window).scroll(function() {
            if($(window).scrollTop() > screen.height*0.6 + (372*3*(page-2)) && s!=0 ) {
                s = 0; console.log('--'+page+'--');
                $('.loading-pro').show();
                $.ajax({
                    url: '/filtered/category?p='+page+'&cat='+cats.join()+'&color='+colors.join()+'&size='+sizes.join(),
                    dataType: 'html',
                    success: function (res) {
                        if(end != res.length) {
                            $('.products.list.items.product-items li:last-child').after($.trim(res));
                            page++;
                            s = 1;
                            end = res.length;
                        }
                        $('.loading-pro').hide();
                    }
                });
            }
        });

    });
</script>

