<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"right top","at":"right bottom"}}}'>

        <li class="level0 nav-0 first last level-top parent ui-menu-item" role="presentation">
            <a href="/" class="level-top1 ui-corner-all" aria-haspopup="true" id="ui-id-0" tabindex="-1" role="menuitem">
                <span class="ui-menu-icon ui-icon ui-icon-carat-1-e"></span><span><img src="<?php echo $block->getViewFileUrl('images/home.png'); ?>" /></span></a>

        </li>

        <?php /* @escapeNotVerified */ echo $_menu; ?>
    </ul>
</nav>
